config/routes.rb
Rails.application.routes.draw do
  
      resources :users
      resources :cities

      post '/login', to: 'users#authenticate'

      post '/signup', to: 'users#create'

      post '/users/:id', to: 'users#create_city'

      # resources :user_cities
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

    has_many :user_cities, dependent: :destroy
    has_many :users, through: :user_cities

end

app/models/user.rb
class User < ApplicationRecord

    has_many :user_cities, dependent: :destroy
    has_many :cities, through: :user_cities

    has_secure_password
 
    def auth_token
        JWT.encode({ id: self.id }, ';lakjs;fajs;lkj;')
    end
    
end

app/models/user_city.rb
class UserCity < ApplicationRecord
    belongs_to :user
    belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API

    attr_reader :current_user

    before_action :define_current_user



    def define_current_user

        begin 

            # request.headers = "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6NX0.aSMTxajJ7erzBRO97b1157V0qs-PIMCHOmvWgLrR4F4"
            token = request.headers['Authorization'].split(' ')[1]
            # type, token = request.headers['Authorization'].split(' ')
            
            payload = JWT.decode(token, ';lakjs;fajs;lkj;')[0]

            # payload, header = JWT.decode(token, '65bc368fbc69306')

            @current_user = User.find(payload['id'])

            if @current_user
                return true
            else
                render json: {
                    error: true,
                    message: 'User does not exist'
                }
            end
        rescue 
            # They are not
            render json: {
                error: true,
                message: 'Invalid Authentication'
            }
        end
    end
 



end

app/controllers/cities_controller.rb
  class CitiesController < ApplicationController
    before_action :set_city, only: [:show, :edit, :update, :destroy]

    # GET /cities
    def index
      cities = City.all
      render json: cities
    end

    # GET /cities/1
    def show
    end

    # GET /cities/new
    def new
      @city = City.new
    end

    # GET /cities/1/edit
    def edit
    end

    # POST /cities
    def create
      @city = City.create(city_params)
      render json: @city
    end

    # Only allow a trusted parameter "white list" through.
    def city_params
      params.permit(:name, :country)

    end
end

    # PATCH/PUT /cities/1
    def update
      if @city.update(city_params)
        redirect_to @city, notice: 'City was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /cities/1
    def destroy
      @city.destroy
      redirect_to cities_url, notice: 'City was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_city
        @city = City.find(params[:id])
      end

      

app/controllers/user_cities_controller.rb
  class UserCitiesController < ApplicationController
    before_action :set_user_city, only: [:show, :edit, :update, :destroy]

    # GET /user_cities
    def index
      @user_cities = UserCity.all
      render json: @user_cities
    end

    # GET /user_cities/1
    def show
    end

    # GET /user_cities/new
    def new
      @user_city = UserCity.new
    end

    # GET /user_cities/1/edit
    def edit
    end

    # POST /user_cities
    def create
      @user_city = UserCity.new(user_city_params)

      if @user_city.save
        redirect_to @user_city, notice: 'User city was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /user_cities/1
    def update
      if @user_city.update(user_city_params)
        redirect_to @user_city, notice: 'User city was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /user_cities/1
    def destroy
      @user_city.destroy
      redirect_to user_cities_url, notice: 'User city was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user_city
        @user_city = UserCity.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def user_city_params
        params.fetch(:user_city, {})
      end
  end

app/controllers/users_controller.rb
  class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :define_current_user, only: [ :authenticate, :create ]

    # GET /users
    def index
      users = User.all
      render json: users
    end

    # GET /users/1
    def show
      user = User.find_by(id: params[:id])
      cities = user.cities
      render json: user
    end

    # GET /users/new
    def new
      user = User.new
    end

    # GET /users/1/edit
    def edit
    end

    def authenticate
      # Find the user by looking for the entered username in Users
      user = User.find_by(username: params[:username])
      # Check if the password they wrote is correct
      if user != nil && user.authenticate(params[:password])
        render json: user, methods: [ :auth_token ]
      else
        render json: {error: true, message: 'Login Failed' }
      end

    end

    # POST /users
    def create
      user = User.create(user_params)
      # byebug # user.errors.full_messages
      render json: user

    end

    # Create City for User

    def create_city

      user = User.find_by(id: params[:id])
      city = City.create(name: params[:name], country: params[:country])
      UserCity.create(user: user, city: city)
      render json: user
      
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.permit(:username, :hometown_city, :hometown_country, :email, :password)
    end

    # PATCH/PUT /users/1
    def update
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        render json: @user
      end
    end

    # DELETE /users/1
    def destroy
      @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      

      

  end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/user_cities_helper.rb
module UserCitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/user_cities/_form.html.erb
<%= form_with(model: user_city, local: true) do |form| %>
  <% if user_city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_city.errors.count, "error") %> prohibited this user_city from being saved:</h2>

      <ul>
      <% user_city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_cities/edit.html.erb
<h1>Editing User City</h1>

<%= render 'form', user_city: @user_city %>

<%= link_to 'Show', @user_city %> |
<%= link_to 'Back', user_cities_path %>

app/views/user_cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Cities</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_cities.each do |user_city| %>
      <tr>
        <td><%= link_to 'Show', user_city %></td>
        <td><%= link_to 'Edit', edit_user_city_path(user_city) %></td>
        <td><%= link_to 'Destroy', user_city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User City', new_user_city_path %>

app/views/user_cities/new.html.erb
<h1>New User City</h1>

<%= render 'form', user_city: @user_city %>

<%= link_to 'Back', user_cities_path %>

app/views/user_cities/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_city_path(@user_city) %> |
<%= link_to 'Back', user_cities_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>